language: go

go:
- "1.16"

services:
- docker
- redis

git:
  depth: 1

notifications:
  email: false

before_install:
- docker pull minio/minio:latest
- docker run -d -p 127.0.0.1:80:9000 minio/minio sh -c '/usr/bin/minio server /data'

script:
- make lint
- make test.coverage
